name: Build wheel

on:
  workflow_call:

jobs:
  build-wheel:
    name: "Build wheel ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install build
      run: pip install build

    - name: Run build (Unix)
      if: runner.os != 'Windows'
      run: python -m build --wheel -Csetup-args="-Dpython.allow_limited_api=true"

    - name: Run build (Windows)
      if: runner.os == 'Windows'
      run: python -m build --wheel -Csetup-args="-Dpython.allow_limited_api=true" -Csetup-args="--vsenv"

    - name: Upload wheel
      uses: actions/upload-artifact@v5
      with:
        name: ${{ matrix.os }}
        path: dist
