name: Run Tests

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  call-build-wheel:
    uses: ./.github/workflows/build_wheel.yml

  run-tests:
    name: "Test (${{matrix.os}}, Python ${{ matrix.python-version }})"
    runs-on: ${{ matrix.os }}
    needs: call-build-wheel

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.12", "3.13"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Download wheel artifact
      uses: actions/download-artifact@v6
      with:
        name: ${{ matrix.os }}

    - name: Install wheel
      run: pip install mesontest --no-index --find-links .

    - name: Install pytest
      run: pip install pytest

    - name: Run tests
      run: pytest
